import { neon } from "@neondatabase/serverless";
import type { LicenseRow, LicenseStore, UpdateRow } from "./licenseRepository.js";

type Sql = ReturnType<typeof neon>;

export class NeonLicenseRepository implements LicenseStore {
  private readonly sql: Sql;

  constructor(databaseUrl: string) {
    this.sql = neon(databaseUrl);
  }

  async migrate(): Promise<void> {
    await this.sql.transaction([
      this.sql`
        CREATE TABLE IF NOT EXISTS licenses (
          key TEXT PRIMARY KEY,
          status TEXT NOT NULL DEFAULT 'active',
          created_at TEXT NOT NULL,
          expires_at TEXT,
          blocked INTEGER NOT NULL DEFAULT 0
        )
      `,
      this.sql`
        CREATE TABLE IF NOT EXISTS activations (
          license_key TEXT NOT NULL,
          device_id TEXT NOT NULL,
          activated_at TEXT NOT NULL,
          PRIMARY KEY (license_key, device_id),
          FOREIGN KEY (license_key) REFERENCES licenses(key)
        )
      `,
      this.sql`
        CREATE TABLE IF NOT EXISTS updates (
          version TEXT PRIMARY KEY,
          notes TEXT NOT NULL,
          link TEXT NOT NULL,
          active INTEGER NOT NULL DEFAULT 1,
          created_at TEXT NOT NULL
        )
      `,
      this.sql`
        CREATE TABLE IF NOT EXISTS audit_log (
          id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          operation TEXT NOT NULL,
          license_key TEXT,
          device_id TEXT,
          result TEXT NOT NULL,
          created_at TEXT NOT NULL
        )
      `,
    ]);
  }

  async getLicense(key: string): Promise<LicenseRow | undefined> {
    const rows = (await this.sql`SELECT * FROM licenses WHERE key = ${key}`) as LicenseRow[];
    const [row] = rows;
    return row as LicenseRow | undefined;
  }

  async listLicenses(): Promise<LicenseRow[]> {
    const rows = await this.sql`SELECT * FROM licenses ORDER BY created_at DESC`;
    return rows as LicenseRow[];
  }

  async createLicense(key: string, expiresAt: string | null): Promise<void> {
    await this.sql`
      INSERT INTO licenses (key, status, created_at, expires_at, blocked)
      VALUES (${key}, 'active', ${new Date().toISOString()}, ${expiresAt}, 0)
    `;
  }

  async setBlocked(key: string, blocked: boolean): Promise<boolean> {
    const rows = (await this.sql`
      UPDATE licenses
      SET blocked = ${blocked ? 1 : 0}, status = ${blocked ? "revoked" : "active"}
      WHERE key = ${key}
      RETURNING key
    `) as Array<{ key: string }>;
    return rows.length > 0;
  }

  async recordActivation(key: string, deviceId: string): Promise<void> {
    await this.sql`
      INSERT INTO activations (license_key, device_id, activated_at)
      VALUES (${key}, ${deviceId}, ${new Date().toISOString()})
      ON CONFLICT(license_key, device_id)
      DO UPDATE SET activated_at = excluded.activated_at
    `;
  }

  async audit(
    operation: string,
    key: string | null,
    deviceId: string | null,
    result: string,
  ): Promise<void> {
    await this.sql`
      INSERT INTO audit_log
        (operation, license_key, device_id, result, created_at)
      VALUES (${operation}, ${key}, ${deviceId}, ${result}, ${new Date().toISOString()})
    `;
  }

  async setUpdate(version: string, notes: string, link: string): Promise<void> {
    await this.sql.transaction([
      this.sql`UPDATE updates SET active = 0`,
      this.sql`
        INSERT INTO updates (version, notes, link, active, created_at)
        VALUES (${version}, ${notes}, ${link}, 1, ${new Date().toISOString()})
        ON CONFLICT(version) DO UPDATE SET
          notes = excluded.notes,
          link = excluded.link,
          active = 1
      `,
    ]);
  }

  async getActiveUpdate(): Promise<UpdateRow | undefined> {
    const rows = (await this.sql`
      SELECT version, notes, link, active
      FROM updates
      WHERE active = 1
      ORDER BY created_at DESC
      LIMIT 1
    `) as UpdateRow[];
    const [row] = rows;
    return row as UpdateRow | undefined;
  }
}
